#!/bin/sh

case "$1" in
  start)
    echo "Loading faulty module and scull"
    /usr/bin/scull_load   
    #Load the fauly module as per usage: /usr/bin/module_load module_name
    /usr/bin/module_load faulty
    /usr/bin/aesdchar_load
    modprobe hello
    ;;
    stop)
    echo "Unloading faulty module and scull"
    #Unload the fauly module as per usage: /usr/bin/module_unload module_name
    /usr/bin/scull_unload 
    /usr/bin/module_unload faulty
    /usr/bin/aesdchar_unload
    rmmod hello
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
